Update server.tsx
Hi, When I ran the project when using styled-component@4.1.6, it hints "TypeError: styleSheet.hasNameForId is not a function", then I fixed it by changing sheet to sheet.instance. I'm wondering why we use sheet instead of sheet.instance there?